remote_theme: epidrome/cover-card@e73ebb1e6373346258583a02b85ac798d1c43b4e

title: okjaybird

avatar: https://avatars.githubusercontent.com/u/1078805
background: andrew-kliatskyi-DQorphiX7oE-unsplash.jpg

github-user: 'okjaybird'
email: 'hello@okjaybird.com'

plugins:
  - jekyll-remote-theme

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']
